# Generated by Django 2.0 on 2021-04-23 02:06

import Scraping.utils
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'قیمت',
                'verbose_name_plural': 'قیمت ها',
            },
        ),
        migrations.CreateModel(
            name='Musicitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='نام کالا')),
                ('your_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='قیمت شما (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Scraping.utils.get_image_path, verbose_name='انتخاب عکس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان')),
                ('value', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='قیمت فعلی(تومان)')),
                ('un_seen_count', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='رویت')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='Scraping.Links', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قیمت',
                'verbose_name_plural': 'قیمت ها',
            },
        ),
        migrations.AddField(
            model_name='links',
            name='musicitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musicitem', to='Scraping.Musicitems', verbose_name='محصول'),
        ),
    ]
