# Generated by Django 2.0 on 2021-04-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='unit',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='واحد'),
        ),
    ]
